In [15]:
# import sys
# sys.path.append('/home/yangxiaoda/CGR')
# from CSD.feature_encoder_test import ImageEncoder
# import torch
# model=ImageEncoder()

# image1='/home/yangxiaoda/CGR/Test_pictures/abstract1.jpg'

# features1=model.encode(image1)
# print(features1[0][0])

In [1]:
import sys
sys.path.append('/home/yangxiaoda/CGR')
from CSD.feature_encoder_test_csd import ImageEncoder
import torch
model=ImageEncoder()

image1='/home/yangxiaoda/CGR/Test_pictures/abstract1.jpg'
image2='/home/yangxiaoda/CGR/Test_pictures/abstract2.jpg'
image3='/home/yangxiaoda/CGR/Test_pictures/abstract3.jpg'
image4='/home/yangxiaoda/CGR/Test_pictures/uk1.jpg'
image5='/home/yangxiaoda/CGR/Test_pictures/uk2.jpg'
image6='/home/yangxiaoda/CGR/Test_pictures/popart1.jpg'
image7='/home/yangxiaoda/CGR/Test_pictures/popart2.jpg'

features1=model.encode(image1)
# print(features1[0][0])
features2=model.encode(image2)
features3=model.encode(image3)
features4=model.encode(image4)
features5=model.encode(image5)
features6=model.encode(image6)
features7=model.encode(image7)

device="cuda" if torch.cuda.is_available() else "cpu"

features1=torch.tensor(features1,dtype=torch.float32).to(device)
features2=torch.tensor(features2,dtype=torch.float32).to(device)
features3=torch.tensor(features3,dtype=torch.float32).to(device)
features4=torch.tensor(features4,dtype=torch.float32).to(device)
features5=torch.tensor(features5,dtype=torch.float32).to(device)
features6=torch.tensor(features6,dtype=torch.float32).to(device)
features7=torch.tensor(features7,dtype=torch.float32).to(device)

ModuleNotFoundError: No module named 'CSD.model'

In [20]:
featurestot=[]
featurestot.append(features1)
featurestot.append(features2)
featurestot.append(features3)
featurestot.append(features4)
featurestot.append(features5)
featurestot.append(features6)
featurestot.append(features7)
featurestot=torch.stack(featurestot).squeeze(1)

print(featurestot.shape)

torch.Size([7, 768])


In [21]:
import torch
import torch.nn.functional as F

# print(features1[0][0])
# print(features1.shape)
# features1=F.normalize(features1,p=2,dim=1)
# print(features1[0][0])
# print(features1.shape)
# featurestot=F.normalize(featurestot,p=2,dim=1)


similarity1=torch.mm(features1,featurestot.t())
similarity2=torch.mm(features2,featurestot.t())
similarity3=torch.mm(features3,featurestot.t())
similarity4=torch.mm(features4,featurestot.t())
similarity5=torch.mm(features5,featurestot.t())
similarity6=torch.mm(features6,featurestot.t())
similarity7=torch.mm(features7,featurestot.t())
print(similarity1)
print(similarity2)
print(similarity3)
print(similarity4)
print(similarity5)
print(similarity6)
print(similarity7)

tensor([[1.0001, 0.6979, 0.6505, 0.5792, 0.4675, 0.5018, 0.5410]],
       device='cuda:0')
tensor([[0.6979, 0.9996, 0.5606, 0.4974, 0.3621, 0.4501, 0.6528]],
       device='cuda:0')
tensor([[0.6505, 0.5606, 1.0000, 0.6096, 0.4786, 0.5262, 0.4469]],
       device='cuda:0')
tensor([[0.5792, 0.4974, 0.6096, 1.0005, 0.7563, 0.5594, 0.4592]],
       device='cuda:0')
tensor([[0.4675, 0.3621, 0.4786, 0.7563, 1.0001, 0.4911, 0.3574]],
       device='cuda:0')
tensor([[0.5018, 0.4501, 0.5262, 0.5594, 0.4911, 1.0002, 0.4412]],
       device='cuda:0')
tensor([[0.5410, 0.6528, 0.4469, 0.4592, 0.3574, 0.4412, 1.0003]],
       device='cuda:0')
